name: 京东每日签到

on:
    workflow_dispatch:
    schedule:
        - cron: "5 0 * * *"
    watch:
        types: [stop]
    repository_dispatch:
        types: jd_daily_bounds

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Run app
              run: npm install
            - run: node app.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE }}
                  SERVER_J_TOKEN: ${{ secrets.SERVER_J_TOKEN }}
